# Generated by Django 4.1.2 on 2022-10-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catefories',
            new_name='categories',
        ),
    ]
